export const path = {
    home: '/',
    reservation: '/reservation',
    lookup: '/lookup',
    promotion: '/promotion',
    register: '/register',
    login: '/login',
    logout: '/logout',
    forgotPassword: '/forgotPassword',
    searchFlight: '/search',
    flightBooking: '/flightBooking',
    flightBookingDetail: '/flightBooking/detail',
    flightBookingPayment: '/flightBooking/payment',
    paymentSuccess: '/payment/success',
    // productList: '/productList',
    // news: '/news',
    // introduce: '/introduce',
    // collection: '/collection',
    // contact: '/contact',
    // cart: '/cart',
    // productDetail: ':nameId',
    // checkout: '/checkout',
    // checkoutAddress: '/checkout/address',
    // checkoutPayment: '/checkout/payment',
    // checkoutThankYou: '/checkout/thankyou',
    profile: '/profile',
    // accountOder: '/account/oder/:nameId',
    changePassword: '/changepassword',
    // updateProfile: '/account/updateprofile',
    // productSearch: '/productSearch',

    // Thêm trang quản lý admin

    admin: '/admin',
    adminDashboard: '/admin/dashboard',
    adminAirport: '/admin/airport',
    adminAirline: '/admin/airline',
    adminAirplane: '/admin/airplane',
    adminPassenger: '/admin/passenger',
    adminContact: '/admin/contact',
    adminPromotion: '/admin/promotion',
    adminFlight: '/admin/flight',
    adminBooking: '/admin/booking'
}
